spring.application.name=reservas_restaurantes

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/restaurante_reservas_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:28252322?!0304Lb}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# Configurações do JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Transaction Management
spring.transaction.default-timeout=30
spring.transaction.rollback-on-commit-failure=true
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED

# SQL Scripts
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql

# Server Configuration
server.port=8080